language: cpp
compiler:
  - gcc
before_script:
 - sudo apt-get update
 - sudo apt-get install libboost-test-dev libboost-program-options-dev 
 - wget http://bitbucket.org/eigen/eigen/get/3.2.1.tar.bz2
 - tar xf 3.2.1.tar.bz2
 - ln -s eigen-eigen-*/Eigen .
 - cd yahttp ; ./autogen.sh; ./configure ; cd ..
script:
 - make -j 4
 - make -j 4 check
notifications:
  email:
    - bert.hubert@netherlabs.nl

